In [2]:
import pandas as pd

In [3]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#indexing 
print(s[0])
print(s[3])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
4

# Series

In [4]:
s = pd.Series([23,24,25,26] , index=["Adam","Eve","Bob","Charlie"])
print(s)

print(s[0])
print(s["Adam"])

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64
23
23

C:\Users\sy117\AppData\Local\Temp\ipykernel_21964\1175448815.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

# Properties of series

-> Homogenous data
-> Vectorized Operations
-> Handle missing value with NaN
-> Mutable values and immutable size

# Dataframe

In [5]:
# creation by dictionary of lists
info = {
    "Name" : ["shashi","roshan","aditya"],
    "Age" : [21,23,21],
    "GPA" : [8,9,9.5]
}

df = pd.DataFrame(info)
print(df , type(df))

print(df.index)  # for getting label of rows
print(df.columns)  # for getting label of column

     Name  Age  GPA
0  shashi   21  8.0
1  roshan   23  9.0
2  aditya   21  9.5 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [6]:
# creation by list of lists

df = pd.DataFrame([["Adam",23],["Bob",21],["Eve",30]], columns =["Name","Age"])

print(df)

   Name  Age
0  Adam   23
1   Bob   21
2   Eve   30

In [7]:
# creation by numpy array
import numpy as np

np_arr = np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(np_arr, columns=["A","B","C"])

df

   A  B  C
0  1  2  3
1  4  5  6

# Reading csv & json file

In [8]:
data = pd.read_csv("employee_data.csv")
print(data)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [9]:
json_data = pd.read_json("employee_data.json")
print(json_data)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

### DataFrame Methods

In [10]:
df = data

df.head()  #starting 5 rows   # df.head(n)  for last n row
df.tail()  #ending 5 rows  # df.tail(2)  for last 2 row

df.sample()   # give a random row 

df.info()   # gives summary of the data

df.shape  # return tuple of no. of row and column

df.describe()   #gives some important values about numerical data

df.columns  # gives whole column in data

df.nunique()  #gives no of unique rows in every column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

# Working on AQI Dataset

In [11]:
# AQI dataset
data = pd.read_csv("globalAirQuality.csv")
data

data.head()
data.tail()

data.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [12]:
# selecting data in given dataset

data["city"]    # for selecting a column data
data[["city","aqi"]]   # for selecting more than one column data

data.loc[2]  # for selecting row through label
data.loc[0:2]  # for selecting multiple rows through label

data.iloc[2]  # for selecting row through index 
data.iloc[0:2]  # for selecting multiple rows through index (end exclusive)

# cells - row,column
data.loc[0:2,["city","aqi"]]  # for selecting row and column

data.iloc[0:3,1:5]   
# data.iloc[0:3,["city","aqi","country"]]  # will show error (reason below)
#iloc accepts only numerical value as the indices are numerical hence need to put columns in form of thier index not value

# cell - selecting single cell (scalar)
data.at[0, "city"]   # select single cell through label
data.iat[0, 2]     # # select single cell through index

'New York'

In [13]:
# filtering of data 

data[data["aqi"] > 100]

data[(data["aqi"] > 100) & (data["temperature"] > 30)]

aqi_data = data[(data["aqi"] > 100) & (data["temperature"] > 30)][["city","aqi"]]

# aqi_data.loc[0]   # will show error cause there is no any label with '0' as pandas preserve the label of dataset
aqi_data.iloc[0]

aqi_data.loc[6]   #label '6' is present after the filter hence will not show error


# filtering of data by querrying - return copy

data.query("aqi > 100 & temperature >30")[["city","aqi"]]

aqi_val = 50
data.query("aqi > @aqi_val")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [14]:
# cleaning the data(handle missing values)

df = pd.read_csv("raw_data.csv")

# isnull() / isna()
df.isnull()   # returns true if it's null value
# df.isna()  # same as isnull()

# isnull().sum()
df.isnull().sum()  # counts no of null values in every column

# dropna()
df.dropna()   # drops row having null value
df.dropna(axis=1) # drops column having null value

# fillna()
df.fillna(0)     # fill passed data at the place of null values

cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()

cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)
cleaned_data

# ffill() / bfill()
df.ffill()   # it fill the last encountered value at the place of null value from forward
df.bfill()  # it fill the last encountered value at the place of null value from backward

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [15]:
# cleaning the data(handle duplicate values)

df = pd.read_csv("raw_data.csv")

# duplicated()
df.duplicated()   # for overall data

df[["country","gender"]].duplicated()  # for specific column

# drop_duplicates()
df2 = df.copy()   # store copy so that will be able to recover 

df.drop_duplicates()   # it does not make changes in original dataset
df.drop_duplicates(inplace = True)  # it make changes in original dataset

df = df2 # for gaining datset back

In [114]:
# cleaning the data(handle datatypes & date_time)

# dtypes
df.dtypes   #returns datatype of each column

#astype()
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64")
print(df2["age"].dtypes)


# to_datetime  -> converts into datetime(timestamp)

date_str = "2025-12-31"
new_dtstr = pd.Series(pd.to_datetime(date_str))
new_dtstr

int64

0   2025-12-31
dtype: datetime64[ns]

In [16]:
# cleaning the data(handle strings)

# str.lower() / str.upper() / str.capitalize()
df["gender"].str.capitalize()

# str.strip()
df["name"].str.strip()

# str.split()
df["name"].str.split("@")

# str.contains("xyz")

df["country"].str.contains("india", case = False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object